### ISSUE TITLE
Any plan for publishing inference code?

### ISSUE THREAD

**Issue by ildoonet** [hessamb/lcnn#1]
Great work.

I want you to publish codes for inference which will help a lot for many people.

**Comment by ildoonet** [comment]
https://github.com/ildoonet/tf-lcnn

I implemented your paper in tensorflow.

But I don't know how to inference efficiently, : https://github.com/ildoonet/tf-lcnn/blob/master/ops/sparse_conv2d.cc

Please guide me with any advice.

Thanks.

**Comment by hessamb** [comment]
Thank! This I think could of use to many people. I'm adding it to README so people can find it more easily.
